"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const head_1 = __importDefault(require("next/head"));
const image_1 = __importDefault(require("next/image"));
const Home_module_css_1 = __importDefault(require("../styles/Home.module.css"));
const Home = () => {
    return (<div className={Home_module_css_1.default.container}>
      <head_1.default>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </head_1.default>

      <main className={Home_module_css_1.default.main}>
        <h1 className={Home_module_css_1.default.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={Home_module_css_1.default.description}>
          Get started by editing{' '}
          <code className={Home_module_css_1.default.code}>pages/index.tsx</code>
        </p>

        <div className={Home_module_css_1.default.grid}>
          <a href="https://nextjs.org/docs" className={Home_module_css_1.default.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={Home_module_css_1.default.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={Home_module_css_1.default.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={Home_module_css_1.default.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={Home_module_css_1.default.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={Home_module_css_1.default.logo}>
            <image_1.default src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>);
};
exports.default = Home;
